# This is a basic workflow to help you get started with Actions

name: r

# Controls when the workflow will run
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-latest
    steps:
      - name: get sdk
        run: curl.exe -o sdk.exe https://download.microsoft.com/download/d/8/f/d8ff148b-450c-40b3-aeed-2a3944e66bbd/windowssdk/winsdksetup.exe
      - name: setup sdk
        run: .\sdk.exe /quiet
      - name: get vs
        run: curl -o vs.exe https://aka.ms/vs/17/release/vs_community.exe
      - name: setup vs
        run: .\vs.exe -q --add Microsoft.VisualStudio.Workload.NativeDesktop --add Microsoft.VisualStudio.Component.VC.ATLMFC --includeRecommended
      - name: get depot tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git depot
      - name: depot export dir
        run: cd depot
      - name: export 
        run: python package_from_installed.py 2022 -w 10.0.22000.0
